name: Lint Test

on: 
    push:
        branches: [master, main]
    pull_request:
        branches: [master, main]

jobs:
    lintTest:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repository
              uses: actions/checkout@v2
            - name: Install dependencies
              run: |
                echo "Running install dependencies"
                npm install
            - name: Run Linting
              run: |
                echo "Running Linting Test"
                npm run lint
              env:
                CI: true

# name: Playwright Tests

# on: 
#     push:
#         branches: [master, main]
#     pull_request:
#         branches: [master, main]

# jobs:
        